Repository tfachmann/MdCollab, pull requests merged in 2020-07, with the labels that each got.

#14 Improve css
  site/index.html
  site/output-styles/coolName.css
  site/output-styles/github.css
  site/styles.css
Labels: css

#27 26-style-selection-for-html-output
  site/index.html
  site/index.js
Labels: featurerequest, javascript

#29 Save md file
  site/index.html
  site/index.js
  site/package.json
  site/styles.css
Labels: javascript
